-- Local Drive Location
--@C:\Users\Sushil\Desktop\DatabaseProject\test_script\test_script_citizen.sql    

-- Author: Sushil Pun
--15/03/2017


/* TESTING CONDITION WHEN CITIZENSHIP NUMBER IS VALID AND INVALID*/

-- VALID CASE
-- BEFORE CREATING PROCEDURE PROC_CUSTOMER_CITIZENSHIP
SELECT 	citizenship_number, first_name, last_name
FROM 	customers
WHERE	citizenship_number = 'CN5130';

-- SHOW CITIZENSHIP_NUMBER	FIRSTNAME	LASTNAME

-- AFTER EXECUTING PROCEDURE PROC_CUSTOMER_CITIZENSHIP
SET SERVEROUTPUT ON
EXECUTE proc_customer_citizenship('CN5130');

-- SQL PLUS PROMPT SHOW CITIZENSHIP_NUMBER, IN NEWLINE FIRSTNAME AND IN NEWLINE LASTNAME


-- INVALID CASE
-- BEFORE CREATING PROCEDURE PROC_CUSTOMER_CITIZENSHIP
SELECT 	citizenship_number, first_name, last_name
FROM 	customers
WHERE	citizenship_number = 'CN130';

-- SQL PLUS PROMPT SHOW NO ROW SELECTED BECAUSE CITIZENSHIP DOESNOT EXIT

-- AFTER EXECUTING PROCEDURE PROC_CUSTOMER_CITIZENSHIP
SET SERVEROUTPUT ON
EXECUTE proc_customer_citizenship('CN130');
-- SQL PLUS PROMPT SHOW CITIZENSHIP NOT FOUND

